name: Update LeetCode Solutions

on:
  workflow_dispatch:       # manually trigger
  schedule:
    - cron: '0 0 * * *'   # optional: run daily at midnight UTC

jobs:
  generate-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

     # - name: Install dependencies
     #   run: pip install json

      - name: Generate Markdown files
        run: |
          python - <<EOF
          import os, json
      
          BASE_DIR = "."
          with open("solved_problems.json") as f:
              problems = json.load(f)
      
          for problem in problems:
              difficulty = problem["difficulty"]
              os.makedirs(os.path.join(BASE_DIR, difficulty), exist_ok=True)
              md_path = os.path.join(BASE_DIR, difficulty, f"{problem['titleSlug']}.md")
              with open(md_path, "w", encoding="utf-8") as f_md:
                  f_md.write(f"# {problem['title']}\n\n")
                  f_md.write(f"**Difficulty:** {problem['difficulty']}\n")
                  f_md.write(f"**Link:** [LeetCode](https://leetcode.com/problems/{problem['titleSlug']}/)\n\n")
                  f_md.write("## Solution\n```python\n")
                  f_md.write(problem.get("solutionCode",""))
                  f_md.write("\n```\n")
                  f_md.write(f"## Stats\n- Runtime: {problem.get('runtime','N/A')}\n- Memory: {problem.get('memory','N/A')}\n")
          EOF

      - name: Commit & Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update LeetCode solutions"
          git push
