name: Update LeetCode Solutions

on:
  workflow_dispatch:       # Manual trigger
  schedule:
    - cron: '0 0 * * *'   # Runs daily at midnight UTC

jobs:
  fetch-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install leetcode-cli
        run: npm install -g leetcode-cli

      - name: Authenticate (optional)
        # Only needed if you want to access private submissions
        run: leetcode user -l "KrizzhSriskantharajah"

      - name: Fetch solved problems and generate MD
        run: |
          mkdir -p Easy Medium Hard
          python generate_md.py

          EOF

      - name: Commit & Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update LeetCode solutions" || echo "No changes to commit"
          git push
